// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

function Printer(Item) {
  var print = function (t) {
    console.log(Curry._1(Item.toString, t));
    
  };
  var printList = function (list) {
    console.log($$String.concat(", ", List.map(Item.toString, list)));
    
  };
  return {
          print: print,
          printList: printList
        };
}

function toString(prim) {
  return String(prim);
}

function print(t) {
  console.log(String(t));
  
}

function printList(list) {
  console.log($$String.concat(", ", List.map(toString, list)));
  
}

var IntPrinter = {
  print: print,
  printList: printList
};

console.log(String(10));

printList({
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: /* [] */0
        }
      }
    });

exports.Printer = Printer;
exports.IntPrinter = IntPrinter;
/*  Not a pure module */
