// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function fib(n) {
  if (n === 0 || n === 1) {
    return 1;
  } else {
    return fib(n - 1 | 0) + fib(n - 2 | 0) | 0;
  }
}

console.log(fib(15));

function gcd(_m, _n) {
  while(true) {
    var n = _n;
    var m = _m;
    if (m === 0) {
      return n;
    }
    _n = m;
    _m = Caml_int32.mod_(n, m);
    continue ;
  };
}

console.log(gcd(99, 363));

exports.fib = fib;
exports.gcd = gcd;
/*  Not a pure module */
