// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var x = 20;

var x$1 = x + 3 | 0;

console.log(x$1);

var message = "hello world";

console.log(message);

exports.x = x$1;
exports.message = message;
/*  Not a pure module */
