// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var greeting = "hello!";

var newScore = 20;

console.log(greeting, newScore);

var score = 10;

exports.greeting = greeting;
exports.score = score;
exports.newScore = newScore;
/*  Not a pure module */
