// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

console.log("Hello World!");

$$String.trim(" extra whitespace\n");

$$String.concat("\n", {
      hd: "line 1",
      tl: {
        hd: "line 2",
        tl: /* [] */0
      }
    });

var s = $$String.sub("Hello World!", 6, 5);

console.log(s);

$$String.make(1, /* "c" */99);

var charArray = [
  /* "H" */72,
  /* "e" */101,
  /* "l" */108,
  /* "l" */108,
  /* "o" */111
];

var s$1 = $$String.init(5, (function (i) {
        return Caml_array.caml_array_get(charArray, i);
      }));

console.log(s$1);

var c = /* "e" */101;

exports.c = c;
exports.charArray = charArray;
exports.s = s$1;
/*  Not a pure module */
