// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");

Jest.describe("Reason Syntax", (function (param) {
        Jest.test("toBe", (function (param) {
                return Jest.Expect.toBe(3, Jest.Expect.expect(3));
              }));
        Jest.test("not toBe", (function (param) {
                return Jest.Expect.toBe(4, Jest.Expect.not_(Jest.Expect.expect(3)));
              }));
        return Jest.test("not_ toBe", (function (param) {
                      return Jest.Expect.toBe(4, Jest.Expect.not__(Jest.Expect.expect(3)));
                    }));
      }));

/*  Not a pure module */
